### PR TITLE
Feature/epic 142 self reset password

### PR DESCRIPTION
**Pull request by daveotengo**
Fixes #

### CODE REVIEW

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo,

Thanks for your contribution.

I see test cases are failing, please make sure all the tests passed, then push your changes.

Thanks,

**Comment by daveotengo** [comment]
Ok @GouthamVadivelmurugan,

I am working on it now.
Will revert when I'm done.

Thanks

**Comment by daveotengo** [comment]
Hi @GouthamVadivelmurugan,

please I'm done please check and revert if there are any issues.

Thanks

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo 

Test cases are still failing, please find the stack trace attached.
[stackTrace13_02_2024.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/14269411/stackTrace13_02_2024.txt)

Could you please verify your merged branches are up to date? I see there are commits behind from the development branch. Please check the attached screenshot.

image

**Comment by daveotengo** [comment]
Hi @GouthamVadivelmurugan,

I decided to run a test on the main (Sormas Foundation) development branch to be sure the failing tests were as a result of the changes I did and also find out if that branch has all the tests passing as you are expecting all my test to pass.

Below is the results

[ERROR] Failures:
[ERROR]   EnvironmentSampleFacadeEjbTest.testGetIndexList:502
Expected: is <Test pathogen 2>
     but: was <Test pathogen>
[ERROR]   ExternalSurveillanceToolGatewayFacadeEjbTest.testIsSharedCase:400 expected: <false> but was: <true>
[ERROR]   AggregateReportFacadeEjbTest.testAggregateReportGetEditData:381 expected: <2> but was: <1>
[ERROR]   AggregateReportFacadeEjbTest.testAggregateReportsSummarize:264 expected: <2> but was: <3>
[INFO]
[ERROR] Tests run: 1077, Failures: 4, Errors: 0, Skipped: 4

That means even in the main development branch the test cases are failing. I realized that below are the failures im seeing on my feature branch so i will fix them and revert

Method <de.symeda.sormas.backend.user.UserFacadeEjb.checkPasswordStrength(java.lang.String)> is not annotated with @DenyAll in (UserFacadeEjb.java:944) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.checkPasswordStrength(java.lang.String)> is not annotated with @PermitAll in (UserFacadeEjb.java:944) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.checkPasswordStrength(java.lang.String)> is not annotated with @RightsAllowed in (UserFacadeEjb.java:944)
Method <de.symeda.sormas.backend.user.UserFacadeEjb.generatePassword()> is not annotated with @DenyAll in (UserFacadeEjb.java:894) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.generatePassword()> is not annotated with @PermitAll in (UserFacadeEjb.java:894) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.generatePassword()> is not annotated with @RightsAllowed in (UserFacadeEjb.java:894)
Method <de.symeda.sormas.backend.user.UserFacadeEjb.getValidLoginRoles(java.lang.String, java.lang.String)> is not annotated with @DenyAll in (UserFacadeEjb.java:920) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.getValidLoginRoles(java.lang.String, java.lang.String)> is not annotated with @PermitAll in (UserFacadeEjb.java:920) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.getValidLoginRoles(java.lang.String, java.lang.String)> is not annotated with @RightsAllowed in (UserFacadeEjb.java:920)
Method <de.symeda.sormas.backend.user.UserFacadeEjb.removeUserAsSurveillanceAndContactOfficer(java.lang.String)> is not annotated with @DenyAll in (UserFacadeEjb.java:1010) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.removeUserAsSurveillanceAndContactOfficer(java.lang.String)> is not annotated with @PermitAll in (UserFacadeEjb.java:1010) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.removeUserAsSurveillanceAndContactOfficer(java.lang.String)> is not annotated with @RightsAllowed in (UserFacadeEjb.java:1010)
Method <de.symeda.sormas.backend.user.UserFacadeEjb.updateUserPassword(java.lang.String, java.lang.String, java.lang.String)> is not annotated with @DenyAll in (UserFacadeEjb.java:885) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.updateUserPassword(java.lang.String, java.lang.String, java.lang.String)> is not annotated with @PermitAll in (UserFacadeEjb.java:885) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.updateUserPassword(java.lang.String, java.lang.String, java.lang.String)> is not annotated with @RightsAllowed in (UserFacadeEjb.java:885)
[ERROR]   CaseFacadeEjbTest.testMergeCaseWithDuplicatedVaccines:2039 expected: <null> but was: <Vaccination card>
[ERROR]   EventDocumentFacadeEjbTest.generateEventHandoutTest:144 expected: <<html>
[ERROR]   ExternalSurveillanceToolGatewayFacadeEjbTest.testIsSharedCase:404 expected: <true> but was: <false>
[ERROR]   ImmunizationFacadeEjbTest.testGetAllSince:176 expected: <COVID-19> but was: <Dengue Fever>
[ERROR]   PersonFacadeEjbTest.testGetPersonsAfter:773
Expected: iterable containing [<Person XNSIUJ-KO6UZQ-6S7DZC-2JYG2HWA>]
     but: no item was <Person XNSIUJ-KO6UZQ-6S7DZC-2JYG2HWA>
[ERROR]   TravelEntryFacadeEjbTest.testGetDeaContentOfLastTravelEntry:296

Nevertheless I have concerns with below test cases failing. Because for this functionality i believe its best to allow all users to have ability to self reset their password so i applied the @PermitAll annotation which is causing the test cases to fail. So i think for such unless you have a different way you want it to be implemented i.e add @RightsAllowed with UserEdit permission  for all users to be able to update their passwords please let me know so that i do that for the test to pass otherwise it has to be ignored so that you set BUILD_SKIP_TESTS=true to be able to compile the application successfully without expecting all the test cases to pass as shown in below image

Screenshot 2024-02-14 171327


Method <de.symeda.sormas.backend.user.UserFacadeEjb.checkPasswordStrength(java.lang.String)> is not annotated with @DenyAll in (UserFacadeEjb.java:944) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.checkPasswordStrength(java.lang.String)> is not annotated with @PermitAll in (UserFacadeEjb.java:944) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.checkPasswordStrength(java.lang.String)> is not annotated with @RightsAllowed in (UserFacadeEjb.java:944)
Method <de.symeda.sormas.backend.user.UserFacadeEjb.generatePassword()> is not annotated with @DenyAll in (UserFacadeEjb.java:894) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.generatePassword()> is not annotated with @PermitAll in (UserFacadeEjb.java:894) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.generatePassword()> is not annotated with @RightsAllowed in (UserFacadeEjb.java:894)
Method <de.symeda.sormas.backend.user.UserFacadeEjb.getValidLoginRoles(java.lang.String, java.lang.String)> is not annotated with @DenyAll in (UserFacadeEjb.java:920) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.getValidLoginRoles(java.lang.String, java.lang.String)> is not annotated with @PermitAll in (UserFacadeEjb.java:920) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.getValidLoginRoles(java.lang.String, java.lang.String)> is not annotated with @RightsAllowed in (UserFacadeEjb.java:920)
Method <de.symeda.sormas.backend.user.UserFacadeEjb.removeUserAsSurveillanceAndContactOfficer(java.lang.String)> is not annotated with @DenyAll in (UserFacadeEjb.java:1010) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.removeUserAsSurveillanceAndContactOfficer(java.lang.String)> is not annotated with @PermitAll in (UserFacadeEjb.java:1010) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.removeUserAsSurveillanceAndContactOfficer(java.lang.String)> is not annotated with @RightsAllowed in (UserFacadeEjb.java:1010)
Method <de.symeda.sormas.backend.user.UserFacadeEjb.updateUserPassword(java.lang.String, java.lang.String, java.lang.String)> is not annotated with @DenyAll in (UserFacadeEjb.java:885) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.updateUserPassword(java.lang.String, java.lang.String, java.lang.String)> is not annotated with @PermitAll in (UserFacadeEjb.java:885) and Method <de.symeda.sormas.backend.user.UserFacadeEjb.updateUserPassword(java.lang.String, java.lang.String, java.lang.String)> is not annotated with @RightsAllowed in (UserFacadeEjb.java:885)

So i will focus on the other failing test cases for now while i wait for you final feedback.

Thanks

**Comment by daveotengo** [comment]
Hello @GouthamVadivelmurugan,

All test cases are passing now please check and give me feedback.

Thanks

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo 

Ok, let me check and get back to you.

Thanks

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo 

I still facing an issue on deployment.
As per the root cause, please make the necessary changes in FeatureType.java, where the "DISEASE_DETAILS" constant is missing.
[stackTrace28_02.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/14440578/stackTrace28_02.txt)

**Comment by daveotengo** [comment]
Hello @GouthamVadivelmurugan,

It's because the Disease Details feature has this line DISEASE_DETAILS(true, true, null, null, null);
in the FeatureType.java class which usually gets inserted or added as a feature so once that feature branch is run, if you come back to run the Password reset feature using the same db you will have issues untill you either drop the database or delete that record from the "featureconfiguration" table. Its adviseable to use to different Databases for the different features to avoid such errors caused by version updates.

Screenshot 2024-02-29 123558

Thanks.

**Comment by daveotengo** [comment]
Hi @GouthamVadivelmurugan,
let me know if you still have issues.

Thanks.

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo 

I have deployed the changes in the test server. There, I could identify some functional issues. I have attached the cases that I have tested, Please find the details below

test1.sormas.org
testuser001: 8NtygEEnjLCh
testuser002: C4TDPRG9H98f

[Password Reset Test Cases.docx](https://github.com/SORMAS-Foundation/SORMAS-Project/files/14527950/Password.Reset.Test.Cases.docx)

**Comment by daveotengo** [comment]
Hello @GouthamVadivelmurugan,

That's good to hear.

Your concerns are well noted but for the 4. I was intentional about it. I decided that since the password was not automatically generated its assumed that the user knows the password in his mind and that is why I decided not to show it because since its user generated it might be easy for someone close by to memorise it.
But if you still want it to show I will do that.

Kindly give me feedback on that.

Thanks

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo 

In case 4, the user clicked on "Generate new password". The password is generated successfully and appended to the 2 fields "Enter new password" and "Confirm new password" and then when the user clicks on save. It saves the password successfully and does not display the generated password. Now the user doesn't know the newly generated password.

Thanks

**Comment by daveotengo** [comment]
Hello @GouthamVadivelmurugan,

I get you. But is that the behaviour you want so that the user clicks on "Generate new password" or you want the user 
to Enter the password by him self? 

Please let me know so that I effect the  changes accordingly
Thanks.

**Comment by daveotengo** [comment]
Hi @GouthamVadivelmurugan,

I can make it such that I allow the user to see the password after they click on "Generate new password" otherwise if they just enter the password I will not show it to them.

I hope that logic is ok. If but if you want me to show the password at all times too let me know thanks.

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo 

Ya please show the password only when the user clicks on "Generate new password".

Thank

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo 

Ya please show the password only when the user clicks on "Generate new password".

Thank

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo 

Also please add
that don't allow the user to set(Save) simple/weak passwords.
The password must contain at least one number, one uppercase, and lowercase letter, one special character and at least 8 or more characters
1. A lowercase letter
2. A capital (uppercase) letter
3. A number
4. Minimum 8 characters
5. A special character

Thanks

**Comment by daveotengo** [comment]
Got it

**Comment by daveotengo** [comment]
Hello @GouthamVadivelmurugan,

I have done the updates you asked me to do and i have pushed but due to internet issues in Ghana I'm unable to synchronize with the upstream development branch so I'm waiting to get good internet to be able to do that.

Meanwhile if you want to test what i have done it's only on this branch and its not up to date with the upstream development branch.

If its compulsory for me to update the branch before you can test then i will inform you when I'm done, that means by then the internet should be fine.

Please let me have you feedback on this.

Thanks.

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo 

Please synchronize with the upstream development branch always

and regarding the "don't allow a weak password to save"
I have tried with the password "12345678" " but it allows me to successfully save the password. Please find the screenshot below
and also you can test this in "test1.sormas.org"

image

**Comment by daveotengo** [comment]
Hello @GouthamVadivelmurugan,

I'm done kindly test.

Thanks.

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo 

Sure, let me test and update you.

Thanks.

**Comment by daveotengo** [comment]
Hi @GouthamVadivelmurugan,

I hope any feedback with the test let me know.

Thanks.

**Pull request merged**
