### PR TITLE
qa-auto/HSP-6559 - Refactoring the sleep method part 2

### PR DESCRIPTION
**Pull request by mk-sgent**

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12925

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12925

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12925

**Comment by mk-sgent** [comment]
Jenkins job:

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3551/allure/#suites/9c2ed62e4e00c2d1efbcc745174ec960/6ba3128402777393/

image

**Comment by mk-sgent** [comment]
Jenkins job:

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3554/allure/#suites/79882de23edbfe835172427429a21275/b744cc2ac3a266dc/

image

**Comment by mk-sgent** [comment]
Jenkins job:

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3555/allure/#suites/8c58061b2ed2b35ae02eed396f7f38ec/a374ae24af1d05ec/

image

**Comment by mk-sgent** [comment]
Jenkins job:

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3556/allure/#suites/79882de23edbfe835172427429a21275/5fbc0ecb750072/

image

**Comment by mk-sgent** [comment]
Jenkins job:

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3557/allure/#suites/79882de23edbfe835172427429a21275/1004035f379cf7d9/

image

**Comment by mk-sgent** [comment]
Jenkins job:

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3558/allure/#suites/ba64af4344a5d1b16948f67eae90e934/18cba88f737ca7cd/

image

**Comment by mk-sgent** [comment]
Jenkins job:

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3559/allure/#suites/79882de23edbfe835172427429a21275/43d24aa5deb54c44/

image

**Pull request merged**
