### PR TITLE
#12861 Date validations between 'Date of sampling' and 'Date and time…

### LINKED ISSUE #12861: Date validations between 'Date of sampling' and 'Date and time of result' of pathogen test should be extended
### Problem Description

Currently, in the web and mobile apps, for human and environment samples, for a sample created with a date of sampling 1st of December, and a pathogen test result with the same date, if the date of sampling is later edited to any date after the 1st of December, there is no validation triggered in the 'Date of sampling' field. 

Additionally, in the mobile app, for human and environment samples, for a sample created with a date of sampling of 1st of December, a pathogen test can be created with a 'Date and time of result' in any day before the 1st of December, and no date validation is triggered for the 'Date and time of result' field.

### Proposed Change

Extend the date validations on human and environment samples and their pathogen tests.

### Added Value/Benefit

Consistency in regards to date validations and correlations between dates in associated entities.

### Acceptance Criteria

- [x] in the web and mobile app, trigger a date validation for the 'Date sample was collected'/'Date of sampling' field of human and environment samples, if the date of sampling is after the 'Date and time of result' of the associated pathogen test;
- [x] in the mobile app, trigger a date validation for the 'Date and time of result' field of pathogen tests associated with human and environment samples, if the 'Date and time of result' is before the 'Date sample was collected'/'Date of sampling'.

### Implementation Details

_No response_

### Mockups

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leventegal-she**
… of result' of pathogen test should be extended

Fixes #12861

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13019

**Review by sergiupacurariu — CHANGES_REQUESTED** [review]
the validator does not work properly yet: it is possible to create a pathogenTest having a reportDate earlier than the collection sample date

**Comment by leventegal-she** [comment]
> the validator does not work properly yet: it is possible to create a pathogenTest having a reportDate earlier than the collection sample date

The validation works  between "Date sample was collected" and "Date and time of result" not between report dates

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13019

**Pull request merged**
