### PR TITLE
HSP-6556 Stabilize "Automate "Bulk sending cases from SORMAS to "Meld…

### PR DESCRIPTION
**Pull request by mk-sgent**

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12916

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12916

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12916

**Comment by mk-sgent** [comment]
Jenkins job:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3522/allure/#suites/03ef468fbeb9479f23a936de20f404be/31873f2f1a14ff63/

image

**Pull request merged**
