### PR TITLE
HSP-6365 Stabilize "Add contact person details to facilities case per…

### PR DESCRIPTION
**Pull request by mk-sgent**

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12734

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12734

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12734

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12734

**Comment by mk-sgent** [comment]
Jenkins jobs:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/allure/#suites/f00677fc6d0acba9c5cc59805c9fdd42/7b3fa04351fc60c4/

image

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3398/allure/#suites/79882de23edbfe835172427429a21275/3e23de1919bc101d/

image

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3399/allure/#suites/03ef468fbeb9479f23a936de20f404be/c753a9d0d8e39a8d/

image

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3401/allure/#suites/f00677fc6d0acba9c5cc59805c9fdd42/7b3fa04351fc60c4/

image

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12734

**Pull request merged**
