### PR TITLE
#12074 Replace Ant with Shell scripts

### LINKED ISSUE #12074: Replace Ant build scripts [3]
### Problem Description

We currently use `Ant` with `maven-ant-tasks` to easily build SORMAS within the IDE and deploy changes to the DEV instance of SORMAS on the local system.

With #11963 we noticed very directly that the Ant tooling runs into incompatibilities with newer Maven versions and plugins or dependencies relying on newer JDKs.

Additionally, it is a bit odd for a developer to need to have a running Ant & Maven installed as command line tool, when the IDE provides also Maven.

### Proposed Solution

1. Replace the features of the Ant targets/functions with means directly with Maven, usable in IDEs Eclipse and IntelliJ. Recreate the build and copy actions in Ant with Maven and link it to the package phase.
2. Keep it as usable as possible for developers to maintain the DEV instance: Provide shell scripts in `sormas-base/dev` (or minimum a documentation [here](https://github.com/SORMAS-Foundation/SORMAS-Project/blob/development/docs/DEVELOPMENT_ENVIRONMENT.md)) of often used Maven commands so that every developer can create Run Configurations in the IDE.
3. Remove all Ant functionality and documentation, remove `sormas-base/build`.

### Acceptance criteria

- Keep the `collect-all` functionality since it's used within the CI pipeline. 
   - [x] Adjust jobs `sormas-Build` in Jenkins when the changes are merged.
   - [x] Adjust job `sormas-Release` in Jenkins before the release happens (don't change early to keep hotfix for 1.85.x working until then).

### Additional Information

Caution for developers: The localized `sormas-base/build.properties` needs to be replaced by `sormas-base/dev.env` with `GLASSFISH_DOMAIN_ROOT` parameter set. Details in the [IDE setup](https://github.com/SORMAS-Foundation/SORMAS-Project/blob/development/docs/DEVELOPMENT_ENVIRONMENT.md#step-5-install-and-configure-your-ide).

- Currently used: Ant and [maven-ant-tasks](https://maven.apache.org/ant-tasks/index.html)
- No drop-in replacement is [maven-resolver-ant-tasks](https://maven.apache.org/resolver-ant-tasks/). I already found out that the _dependencies_ feature lacks many of the parameters we currently use with our patched maven-ant-tasks.

### PR DESCRIPTION
**Pull request by StefanKock**
Fixes #12074

Progress documentation:
- [x] Working build targets
- [x] Working collect targets
- [x] Working deploy target
- [x] Improved documentation for developers
- [x] Removed Ant toolchain and mentioning
- [x] Tested with Eclipse
- [x] Tested wit IntelliJ

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12193

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12193

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12193

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12193

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12193

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12193

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12193

**Review by MateStrysewske — APPROVED** [review]

**Pull request merged**
