### PR TITLE
Feature/epic 141 dashboard disease clickable details

### PR DESCRIPTION
**Pull request by daveotengo**
Fixes # 141

### CODE REVIEW

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo,

Please find the review comments below and kindly make the necessary changes.

Test cases are failing with,
1. DiseaseBurdenDTO.java must be an @AuditedClass
2. Please verify all the properties in the captions.properties file must be configured in the Constants.java file. Please note that it must be defined in alphabetical order.

I am not sure about your other changes yet. Please make sure that all the test cases should be passed and then you can check in your changes.

**Comment by daveotengo** [comment]
Hello Goutham, 

That’s Okay.

I will do that by tomorrow and revert.

Thanks.
David Oteng

**Comment by daveotengo** [comment]
Hi @GouthamVadivelmurugan ,

All the Test Cases pertaining to my changes have passed.
Please check and revert.

Thanks.

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo 

When I run the test cases I am facing test failures and attached the stack trace of it, Please go through it and let me know.
[Epic_12880_testReport.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/14236413/Epic_12880_testReport.txt)

**Comment by daveotengo** [comment]
Okay sure.

I will revert

Thanks

**Comment by daveotengo** [comment]
Hello @GouthamVadivelmurugan,

Please check and revert if there are any issues.

Thanks

**Comment by GouthamVadivelmurugan** [comment]
Hi @daveotengo

Test cases are still failing, please find the stack trace attached.
[stackTrace13_02_2024.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/14274035/stackTrace13_02_2024.txt)

Could you please verify your merged branches are up to date? I see there are commits behind from the development branch. Please check the attached screenshot.
image

**Comment by daveotengo** [comment]
Hi @GouthamVadivelmurugan,

I decided to run a test on the main (Sormas Foundation) development branch to be sure the failing tests were as a result of the changes I did and also find out if that branch has all the tests passing or not as you are expecting all my test to pass.

Below is the results

[ERROR] Failures:
[ERROR]   EnvironmentSampleFacadeEjbTest.testGetIndexList:502
Expected: is <Test pathogen 2>
     but: was <Test pathogen>
[ERROR]   ExternalSurveillanceToolGatewayFacadeEjbTest.testIsSharedCase:400 expected: <false> but was: <true>
[ERROR]   AggregateReportFacadeEjbTest.testAggregateReportGetEditData:381 expected: <2> but was: <1>
[ERROR]   AggregateReportFacadeEjbTest.testAggregateReportsSummarize:264 expected: <2> but was: <3>
[INFO]
[ERROR] Tests run: 1077, Failures: 4, Errors: 0, Skipped: 4

That means even in the main development branch the test cases are failing. I realized that below are the failures im seeing on my feature branch so i will fix them and revert.

[ERROR]   CaseFacadeEjbTest.testMergeCaseWithDuplicatedVaccines:2039 expected: <null> but was: <Vaccination card>
[ERROR]   DashboardFacadeEjbTest.testDiseaseBurdenForDashboard:248 expected: <3> but was: <4>
[ERROR]   ImmunizationFacadeEjbTest.testGetAllSince:176 expected: <COVID-19> but was: <Monkeypox>
[ERROR]   PersonFacadeEjbTest.testGetPersonsAfter:773
[ERROR]   TaskFacadeEjbTest.testGetAllActiveTasksBatched:500 expected: <ZZZZZZ-ZZZZZZ-ZZZZZZ-ZZZZZZ> but was: <SCM7PQ-V2ITTI-SXG3SL-DWWBCMOI>

I have also updated the feature branch with the upstream/development branch.

Thanks

**Comment by daveotengo** [comment]
Hi @GouthamVadivelmurugan all test pass now you can check and give me feedback.

Thanks.

**Pull request merged**
