### PR TITLE
HSP-6383_2 Stabilize "Test Inactive Destrict Feauture for Travel Entr…

### PR DESCRIPTION
**Pull request by mk-sgent**

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12899

**Comment by mk-sgent** [comment]
Jenkins job result:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3497/allure/#suites/f9be4abe678aea0e2671bf538229b51e/79d2f7e60f6c6279/

image

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12899

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12899

**Pull request merged**
