### PR TITLE
#12485 - redirect after sample delete to associated case's page

### LINKED ISSUE #12485: [Samples] Return to case after deleting a sample from the case [1]
### Discussed in https://github.com/SORMAS-Foundation/SORMAS-Project/discussions/12009

<div type='discussions-op-text'>

<sup>Originally posted by **AliciaRaber** April 17, 2023</sup>
### Problem Description

When you are in a case and click on the pen-button in the samples section the system change to samples and display the simple sample. In this overview it is possible to delete the sample. After deleting the sample the system remains in the sample directory

### Proposed Change

After deleting a sample from case view set trigger to return to the case from the deleted sample.

### Added Value/Benefit

For a better traceability and case management the user can work on the same case without have to search again for the case.

### Acceptance Criteria

- [ ]
- [ ]
- [ ]

### Implementation Details
image

image

image

image

### Mockups

_No response_

### Additional Information

_No response_</div>

### PR DESCRIPTION
**Pull request by carina29**
Fixes #12485

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12756

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12756

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
Not tested it yet, but purely based on looking at the code: We should only go back to the case/contact/ep when we came through that direction in the first place. If I enter a sample through the sample directory, I still want to go back to the sample directory after deleting it, not to its associated entity.

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12756

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12756

**Review by MateStrysewske — APPROVED** [review]

**Pull request merged**
