### PR TITLE
#11463 - Add bulk action progress window to "Archive" and "Dearchive"…

### LINKED ISSUE #11463: Add bulk action progress window to "Archive" and "Dearchive" bulk actions [2]
### Problem Description

#11597 has introduced a progress window for the "Edit" bulk actions. This window needs to be applied to other bulk actions as well to be consistent and because it's a lot more user-friendly.

### Proposed Change

Add the progress window to the "Archive" and "Dearchive" bulk actions of all directories.

### Acceptance Criteria

- [x] All "Archive" and "Dearchive" bulk actions in all directories use the bulk action progress window introduced in #11597 when at least 40 entries are selected
- [x] The respective backend calls are done in batches of 20 entities when at least 40 entries are selected
- [x] The bulk action also works in the case detailed and contact detailed directories, which use different grids
- [x] Cancelling the action before it finishes leaves the selected entries that have not yet been processed still selected (as implemented in #11597)

### PR DESCRIPTION
**Pull request by sergiupacurariu**
… bulk actions

Got a bit bigger change then excepted but I wanted to have archive/dearchive feature controlled from a single place instead of having each page implement it's own. Also got rid of big switch statments in infrastructure archive/dearchive moethods. 

Fixes #11463

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12086

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12086

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12086

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12086

**Review by carina29 — CHANGES_REQUESTED** [review]

**Review by carina29 — APPROVED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12086

**Pull request merged**
