### PR TITLE
HSP-6376 Stabilize Edit, save and check all fields of a new case - se…

### PR DESCRIPTION
**Pull request by mk-sgent**

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12757

**Comment by mk-sgent** [comment]
Jenkins jobs:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3411/allure/#suites/79882de23edbfe835172427429a21275/64856d39a75d1064/

image


image

This failing is caused by this bug: https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12612 so I decided to ignore this failing result and I approve it to merge into development

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12757

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12757

**Pull request merged**
