### PR TITLE
#12706 - Display environment task details

### LINKED ISSUE #12706: Display the name of environment, region and district for tasks associated with environments in the 'Tasks' directory grids [2]
### Problem Description

The name of environment, the region and the district are not displayed in the 'Tasks' grids for tasks associated with environments.

### Proposed Change

In the 'Tasks' directory on the web and mobile app, display the name of the environment, the region and the district associated with the task for tasks of environments (similar to how we display these already for tasks associated with other main entities).

### Added Value/Benefit

Consistency in the display of information.

### Acceptance Criteria

- [ ] the data in the fields is confidential based on access - jurisdiction, access to sensitive and personal data within jurisdiction or outside jurisdiction;
- [ ] in the web app - display the name of the environment and UUID in grey between the parentheses after the UUID of the environment, the region and the district in their respective columns (those from the location of the environment);
- [ ] in the mobile app - display the name of the environment under the 'Task type' (similar to how we display for the other entities);

### Implementation Details

_No response_

### Mockups

_No response_

### Additional Information

Current display in the web app:
image

Current display in the mobile app for environment tasks:
image

Current display in the mobile app for tasks associated with other entities than environments:
image

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #12706

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12812

**Review by leventegal-she — CHANGES_REQUESTED** [review]
I don't see any changes regarding to the android app

**Comment by MateStrysewske** [comment]
Totally missed that for some reason, fixed

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12812

**Review by leventegal-she — APPROVED** [review]

**Pull request merged**
