### PR TITLE
Feature 12500 environment sample forms mobile

### LINKED ISSUE #12500: Add environment sample create and edit forms for the mobile app [5]
### Feature Description

https://github.com/SORMAS-Foundation/SORMAS-Project/issues/11721 has introduced a new environment sample entity. Create and edit forms are needed for users to be able to create new environment samples in the mobile app.

### Added Value/Benefit

Users can create environment samples required for one health surveillance.

### Acceptance Criteria

- [x] Creation and edit forms for environment samples have been added with the following fields and headings:
  - Heading: "Laboratory sample"
    - UUID (read only; caption: Sample ID)
    - Environment name (read only)
    - Read-only label with the report date and reporting user (as already implemented for samples)
    - Date of sampling (required)
    - Sample material (required)
    - Specify sample material (if sample material == other, required in this case)
    - Field sample ID
  - Heading: Sample measurements
    - Volume (in mL)
    - Turbidity (in NTU)
    - Temperature (in °C) - pre-fill with values from -20 to +100 °C in steps of 0.1 (see symptoms for reference)
    - Total chlorine residue (mg/L)
    - pH value 
    - Weather condition at time of sampling - display each possible enum value as an individual checkbox
    - Heavy rain in the last 24 hours before sampling?
  - Heading: "Location of sampling site"
    - Location form (region, district, gps lat and gps lon required; location of the environment for which the sample is created is copied over and form is disabled by default)
    - Checkbox "Location differs from environment location" - if checked, clear and enable the location form; if unchecked, disable it and fill it with the environment location again; show this checkbox ABOVE the location form
  - Heading: "Sample management"
    - Laboratory - required
    - Laboratory details (if generic laboratory has been selected)
    - Subheading: "Requested pathogens to be tested"
    - Checkboxes for each pathogen in the system, similar to the requested pathogen tests for samples
    - Other requested pathogens to be tested
    - Checkbox "Sent/dispatched"
    - Dispatch date and dispatch details only if checkbox is checked
    - Checkbox "Received"
    - Receival date and lab sample ID only if checkbox is checked
    - Specimen condition
    - General comment
- [x] Environment sample entries in the list can be opened and bring up the edit form
- [x] An additional view for environments has been added that lists all environment samples in that environment
- [x] A button to create new environment samples has been added to the environment sample list for individual environments; creating environment samples through the general environment sample list is not possible
- [x] Ensure that creating an environment sample with the location of an environment does not actually use the same location entity, but just copies over the values
- [x] Ensure that the form is properly read-only for users without the necessary jurisdiction and who are not the reporting users
- [x] Users with the `ENVIRONMENT_SAMPLE_EDIT_DISPATCH` user right can edit everything up until the "Received" checkbox, and only if they're the reporting user; receival information is not editable in the mobile app at all

### Implementation Details

_No response_

### Mockups

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #12500

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12526

**Review by leventegal-she — CHANGES_REQUESTED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12526

**Review by leventegal-she — CHANGES_REQUESTED** [review]
region, district, gps lat and gps lon are not required in the location of sample required

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12526

**Review by leventegal-she — APPROVED** [review]

**Pull request merged**
