### PR TITLE
Test for the configuration for New Caledonia and its subcontinent association.

### PR DESCRIPTION
**Pull request by hms-sgent**
Small changes in scenario for the configuration for Germany and its subcontinent association.

Fixes #

### CODE REVIEW

**Comment by hms-sgent** [comment]
image

**Comment by hms-sgent** [comment]
image

**Comment by hms-sgent** [comment]
image

**Review by mk-sgent — APPROVED** [review]

**Comment by hms-sgent** [comment]
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/1099/allure/
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/1100/allure/
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/1101/allure/

**Pull request merged**
