### PR TITLE
qu-auto/SORQA-1037 Stabilize DEMIS tests regarding running on multipl…

### PR DESCRIPTION
**Pull request by hms-sgent**
…e threads.

Fixes #

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12266

**Comment by hms-sgent** [comment]
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3043/allure/#behaviors/acf41b5e4fe9b937bc920c16fee1685f/1951787e24d7ec7f/
image

**Comment by hms-sgent** [comment]
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3044/allure/#behaviors/da5cf18cdc518fefefcb227cac6ec0b3/63ffc1459e431dc3/
image

**Comment by hms-sgent** [comment]
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3046/allure/#behaviors/0a358d1c45f6b7e80da4b1e4d9033801/1d322407f1c85033/

image

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12266

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12266

**Pull request merged**
