### PR TITLE
#12902 hide jurisdiction related fields from cases bulk edit form

### LINKED ISSUE #12902: Hide the jurisdiction related fields from the 'Edit cases' form in bulk edit mode [1]
### Problem Description

When the featuretype 'HIDE_JURISDICTION_FIELDS' in enabled we do not show in edit and creation forms the fields related to the jurisdiction - responsible region, district, community. But in bulk edit mode, in the cases directory, we still show them.

image

After the edit is done (select a different region, district than those that are set as default) - if the user goes to the regular edit pages of cases they can now see in the 'Place of stay section' the fields for region, district and community that were previously hidden.

### Proposed Change

Hide the responsible region, district and community fields from the 'Edit cases' form in bulk edit mode.

### Added Value/Benefit

Consistency.

### Acceptance Criteria

- [x] hide the fields region, district and community from the 'Edit cases' form in bulk edit mode when the hide jurisdiction fields feature is enabled;
- [x] consider instead the default values set for region, district and community;
- [x] the user should still be able to change the place of stay - the option for home still present, the option for facility still present - but only facilities from the default jurisdiction being possible to be selected (just as in the regular edit forms of cases);

### Implementation Details

_No response_

### Mockups

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by carina29**
Fixes #12902

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12910

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12910

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12910

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12910

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12910

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12910

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12910

**Review by MateStrysewske — APPROVED** [review]

**Pull request merged**
