### PR TITLE
#12957 Inconsistent and not pre-filled jurisdiction in immunization d…

### LINKED ISSUE #12957: Filters in the immunizations directory show all regions and districts even for users restricted by jurisdiction
### Bug Description

In the Immunizations directory, for a user restricted by jurisdiction, the filters for Region, District and Community show all the available infrastructure data, regardless of the user's jurisdiction. Additionally, the district filter is not displayed at all.

The user restricted up to district 

### Reproduction Steps

1. Log in the app with a Surveillance Officer restricted by Region1 District 1;
2. Navigate to the Immunizations directory;
3. Open the filters for Region, District and Community.
Actual behavior: All infrastructure data associated with those filters is visible for the user.

### Expected Behavior

The filters for Region, District and Community should be read only and prefilled with the data of the logged in user's responsible jurisdiction.

I: If user is of National jurisdiction - all filters should be visible and editable;
II: If user is of Regional jurisdiction - region filter should be prefilled with the user's assigned region, district and community filters should be enabled and dropdowns should contain the values from the the user's region;
III: If user is of District jurisdiction - region and district filters should be read only and prefilled with the user's assigned region and district; community filter should be editable and dropdown should contain communities from the user's district;
IV: If user is of Community Jurisdiction or facility jurisdiction - the filters should be read only and prefilled with the users assigned jurisdiction.

### Affected Area(s)

Web app

### SORMAS Version

1.95.0

### Android version/Browser

Chrome

### User Role(s)

Default Surveillance Officer

### Server URL

https://test.sormas.netzlink.com/sormas-ui/ and local machine 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leventegal-she**
…irectory for users restricted by jurisdiction

Fixes #12957

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12964

**Comment by sergiupacurariu** [comment]
Let's have a Surveillance Supervisor (having Region jurisdiction) logged in. The Immunization filters show only the accessible District and Community fields. The region field is not visible while as per requirement no 2 from "Expected behavior" section of the connected ticket the Region should be prefilled with users Region. Also it is not consistent with a Surveillance Officer (which has District jurisdiction) where District is prefilled, visible and readOnly. The same situation should be found when a user with Region jurisdiction is logged in meaning the Region field in this case should be prefilled, visible and readOnly.

**Review by sergiupacurariu — CHANGES_REQUESTED** [review]
Let's have a Surveillance Supervisor (having Region jurisdiction) logged in. The Immunization filters show only the accessible District and Community fields. The region field is not visible while as per requirement no 2 from "Expected behavior" section of the connected ticket the Region should be prefilled with users Region. Also it is not consistent with a Surveillance Officer (which has District jurisdiction) where District is prefilled, visible and readOnly. The same situation should be found when a user with Region jurisdiction is logged in meaning the Region field in this case should be prefilled, visible and readOnly.

**Comment by leventegal-she** [comment]
> Let's have a Surveillance Supervisor (having Region jurisdiction) logged in. The Immunization filters show only the accessible District and Community fields. The region field is not visible while as per requirement no 2 from "Expected behavior" section of the connected ticket the Region should be prefilled with users Region. Also it is not consistent with a Surveillance Officer (which has District jurisdiction) where District is prefilled, visible and readOnly. The same situation should be found when a user with Region jurisdiction is logged in meaning the Region field in this case should be prefilled, visible and readOnly.

The region field is not visible because of consistency reasons. I know the ticket requests it but if you check the case, contact or other directories, the region filter is not visible for users below national level and the rest of the jurisdiction fields are always visible

**Comment by sergiupacurariu** [comment]
> > Let's have a Surveillance Supervisor (having Region jurisdiction) logged in. The Immunization filters show only the accessible District and Community fields. The region field is not visible while as per requirement no 2 from "Expected behavior" section of the connected ticket the Region should be prefilled with users Region. Also it is not consistent with a Surveillance Officer (which has District jurisdiction) where District is prefilled, visible and readOnly. The same situation should be found when a user with Region jurisdiction is logged in meaning the Region field in this case should be prefilled, visible and readOnly.
> 
> The region field is not visible because of consistency reasons. I know the ticket requests it but if you check the case, contact or other directories, the region filter is not visible for users below national level and the rest of the jurisdiction fields are always visible

Indeed the other directories have the same behavior. So all directories show the District visible and readOnly for users with District jurisdiction (same also for Community jurisdiction) but do not show the Region in case of Region Jurisdiction. But this could be subject to a different discussion.

**Review by sergiupacurariu — APPROVED** [review]

**Pull request merged**
