### PR TITLE
SORQA-1014 Stabilize "Add contact person details to facilities case …

### PR DESCRIPTION
**Pull request by mk-sgent**

### CODE REVIEW

**Comment by mk-sgent** [comment]
Jenkins report:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/2944/allure/#suites

image

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12194

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12194

**Comment by mk-sgent** [comment]
Oher jobs:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/2946/allure/

image

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/2947/allure/#suites

image

**Review by hms-sgent — APPROVED** [review]

**Pull request merged**
