### PR TITLE
qu-auto/SORQA-957correction Test send simple Case from SORMAS to "Meldesoftware". Steps description: SurvNet generated renamed into SORMAS generated.

### PR DESCRIPTION
**Pull request by hms-sgent**
Fixes #

### CODE REVIEW

**Comment by hms-sgent** [comment]
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/2846/allure/#behaviors/9613102b9d864cb08dab8eaf024f077e/5c7d1c3c0eb0bdcb/

**Comment by hms-sgent** [comment]
image

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12019

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12019

**Pull request merged**
