### PR TITLE
Feature 12028 disease variant bulk edit

### LINKED ISSUE #12028: Add the disease variant to the edit forms of cases in Bulk action [1]
### Problem Description

Currently in Bulk mode you are not able to select a number of cases and assign a disease variant to the selected ones. It's only possible to assign a disease or change other data

### Proposed Change

Add a dropdown to select a disease variant if there are any for the selected disease so it can be selected and changed in bulk mode.

### Added Value/Benefit

Saves time as you don't have to go into every case to add the variant.

### Acceptance Criteria

- [ ] The bulk edit form contains a checkbox "Change disease variant" with a disease variant field and a disease variant details field
- [ ] The disease variant field is shown when "Change disease" has been selected and a disease that has disease variants on the system has been selected
- [ ] The disease variant details field is shown when a disease variant with the "hasDetails" property set to true has been selected
- [ ] Saving the bulk data form updates the disease variant for all selected cases

### Implementation Details

_No response_

### Mockups

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leventegal-she**
Fixes #12028

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12352

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
Looks good, apart from the two shell scripts that somehow made their way into this PR and shouldn't be there. Please remove them from the list of committed files. :)

**Comment by leventegal-she** [comment]
> Looks good, apart from the two shell scripts that somehow made their way into this PR and shouldn't be there. Please remove them from the list of committed files. :)

I've just made them executable. I would keep so others working on mac or linux will be able to execute them  without changing and keeping in mind to not commit

**Comment by MateStrysewske** [comment]
@leventegal-she Could you do that directly on the dev branch then? I'd like it to not get mixed into a feature issue like this

**Comment by leventegal-she** [comment]
Created new PR https://github.com/SORMAS-Foundation/SORMAS-Project/pull/12358

**Pull request closed without merging**
