### PR TITLE
qa-auto/HSP-6579 Stabilize "Create and check a new task data" - added…

### PR DESCRIPTION
**Pull request by mk-sgent**

### CODE REVIEW

**Comment by mk-sgent** [comment]
Jenkins job:
https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3565/allure/#suites/dd4b18beb479879479ed3727ef2674ce/8673a1d66244eced/

image

**Comment by mk-sgent** [comment]
Jenkins jobs:

https://jenkins.sormas.netzlink.com/view/SORMAS-E2eTests/job/sormas-RunE2eTests-branch/3566/allure/#suites/dd4b18beb479879479ed3727ef2674ce/128fc3692c30b45d/

image

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12952

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12952

**Pull request merged**
