### PR TITLE
#12820 - Align contact information icon

### LINKED ISSUE #12820: Align contact information icon for reporting user to the left
### Problem Description

Issue https://github.com/SORMAS-Foundation/SORMAS-Project/issues/6667 added contact information on edit forms for many entities. The icon is far from the caption "reporting user" and closer to the boxes (e.g task) on the right. The information in the pop-up does not contain text linking it to the reporting user information

### Proposed Change

Bring the icon to the left, as close to the caption as possible
image

### Added Value/Benefit

Improve design and understanding of captions

### Acceptance Criteria

- [ ] The eys icon is as close to the caption "responsible user" as possible
- [ ] If the resolution of the browser size is reduced, both the caption and icon stay together
- [ ]

### Implementation Details

_No response_

### Mockups

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by carina29**
Fixes #12820

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12888

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
The potential issue with this implementation is that longer user names will be cropped, and there's no way of displaying them fully. I have two suggestions on how to solve this; not sure right now which one I like most, maybe you can try out both of them and see which one you like more:

a) Move the eye icon to the left of the reporting user field and making it only one column wide to ensure it's next to the reporting user field
b) Add a "Username" field to the contact information popup that displays the name of the reporting user (so that, if it's cropped in the form, users can still open the popup and check out the full name)

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12888

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12888

**Review by MateStrysewske — APPROVED** [review]

**Pull request merged**
