### PR TITLE
#13150 automatic manual case classification customization per disease

### LINKED ISSUE #13150: Enable/Disable Automatic/Manual Case Classification Customization Per Disease [2]
### Feature Description

Currently, it is not possible to configure the "Case Classification" and "Automatic Case Classification" options individually for each disease in SORMAS.
Implement the option to individually configure the "Case Classification" and "Automatic Case Classification" for each disease in SORMAS.
Allow the configuration to be managed through the SORMAS Properties settings file.
The following should be the default values:

- Manual Case Classification Calculation: Enabled
- Automatic Case Classification: Enabled

### Added Value/Benefit

Introducing this functionality would greatly improve the workflows of public health authorities by allowing more flexibility in managing case classifications based on specific disease needs.
This feature will enable health departments to adjust case classification workflows according to the specific requirements of different diseases, increasing flexibility and efficiency in case management.

### Acceptance Criteria

- [x] A configurable setting to enable/disable for all diseases at once:
- [x] A configurable setting for each disease in the SORMAS Properties to enable/disable:

Automatic Case Classification
Manual Case Classification Calculation

- [x] Defaults should be:

Manual Case Classification Calculation: Enabled
Automatic Case Classification: Enabled

- [x] SORMAS Admins should be able to customize these settings without any further technical intervention.

### Implementation Details

_No response_

### Mockups

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leventegal-she**
Fixes #13150

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13152

**Comment by sergiupacurariu** [comment]
Since we revise the Case Classification feature I would add a pop up window to inform the user about how case classification can be changed manually. Meaning the case classification cannot be manually changed unless it is the only change on the case. If there is a single change the automatic calculation will be triggered which overrides the manual change.

**Comment by sergiupacurariu** [comment]
please update the Server settings from wiki related to "feature.automaticcaseclassification". https://github.com/sormas-foundation/SORMAS-Project/wiki/Server-Configuration-Options

**Review by sergiupacurariu — APPROVED** [review]

**Comment by leventegal-she** [comment]
Added issues:
[Manual case classification notification](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/13162)
[Update the Server configuration wiki after release 1.99](https://github.com/SORMAS-Foundation/SORMAS-Project/issues/13163)

**Pull request merged**
