### PR TITLE
[#7507] use dependabot for maven

### LINKED ISSUE #7507: Enable automatic dependabot PRs [1]
### Problem Description

Right now, we are managing our dependencies manually which is slow, error prone, and bears unnecessary risks. 

### Proposed Solution

 - Provide `dependabot.yml` to configure automated updates.
 - Define artifacts to ignore: vaadin dependencies

### Possible Alternatives

Keep clustering dependency updates in bigger tickets and lesser steps to keep stack tested at that point.

### Additional Information

Wait for #11032 and #10499 to be merged to have a clean baseline.

### PR DESCRIPTION
**Pull request by JonasCir**
Fixes #7507

What is missing

- [x]  is to add the needed [ignored](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore) dependencies
- [x] ~~gradle is not working. If you take a look at the dependency page, you notice gradle won't show up there, hence no updates for it either. This is caused by [this](https://github.com/orgs/community/discussions/11117). This could be fixed by this [action](https://github.com/marketplace/actions/gradle-dependency-submission) as described in the official [docs](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api#using-pre-made-actions)~~ meanwhile this is working

We can auto-label and assign reviewers, if we want to configure this.

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11692

**Comment by MartinWahnschaffe** [comment]
Created a fork and removed all limitations for created PRs here:
https://github.com/MartinWahnschaffe/SORMAS-Project

It has created multiple PRs for the same dependency of sormas-base:
grafik

Not sure why it has created a PR for vaadin in sormas-backend, but not in sormas-rest or another module. Based on the maven tool in IntelliJ, this is not a relevant dependency for sormas-backend.

Tried to use the dependabot commands to ignore dependencies:
https://github.com/MartinWahnschaffe/SORMAS-Project/pull/50
Seems to take some time to re-act. So far nothing has happened.

**Comment by MartinWahnschaffe** [comment]
@StefanKock I have validated the dependabot script and added the payara dependencies to the ignore list.
Now I'd like to have a look at this and the [resulting PR list](https://github.com/MartinWahnschaffe/SORMAS-Project/pulls) with you.

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11692

**Review by MartinWahnschaffe — APPROVED** [review]

**Comment by MartinWahnschaffe** [comment]
@StefanKock Please review.
Supposed to be merged after the 1.85.0 release, so we can immediately take care of the listed dependency updates.

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11692

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11692

**Review by StefanKock — COMMENTED** [review]
- Wait for #11963 to be merged before.
- Where is defined, that pull requests are labelled with `dependencies`, `java`?

**Comment by JonasCir** [comment]
> Where is defined, that pull requests are labelled with dependencies, java?

Probably the default labeling I assume, you can configure the used labels freely IIRC

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11692

**Pull request merged**
