### PR TITLE
#12810 Hide jurisdiction-related filters and columns if the HIDE_JURI…

### LINKED ISSUE #12810: Hide jurisdiction-related filters and columns if the HIDE_JURISDICTION_FIELDS feature is enabled [2]
### Feature Description

Some filters and columns that are still shown even if the option to hide jurisdiction fields introduced in https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12550 is enabled need to be hidden.

### Added Value/Benefit

Consistency; users would get confused if jurisdiction-related filters and columns are still shown.

### Acceptance Criteria

If the `HIDE_JURISDICTION_FIELDS` feature is enabled:

- [x] Hide the jurisdiction-related filters and columns from the case directory except facilities; ensure that the facility-related filters are enabled and filled based on the default jurisdictions
- [x] Hide the jurisdiction-related filters and columns from the sample directory (except laboratory) - for both human and environment samples
- [x] Hide the jurisdiction-related filters and columns from the environment directory
- [x] Hide the jurisdiction-related filters and columns from the person directory
- [x] Hide the jurisdiction-related filters and columns from the task directory
- [x] Hide the jurisdiction-related filters from all four dashboards and the "last reported district" and "outbreak districts" elements from the surveillance dashboard
- [x] Hide the region, district and community fields from the case line listing feature

### Implementation Details

_No response_

### Mockups

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by leventegal-she**
…SDICTION_FIELDS feature is enabled

Fixes #12810

I did hiding the jurisdiction filters for a few more pages then requested but it's controlled from a single place. So more has been done with less code

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12891

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12891

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12891

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12891

**Review by MateStrysewske — APPROVED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12891

**Pull request merged**
