### PR TITLE
#11900 - Change all references to sormas-foundation

### LINKED ISSUE #11900: Update SORMAS-Project GitHub links to the new URL within SORMAS-Foundation [2]
### Problem Description

The SORMAS-Project repository wil be moved from the HZI-Braunschweig organization ot SORMAS-Foundation, effectively changing the URL from https://github.com/hzi-braunschweig/SORMAS-Project to https://github.com/sormas-foundation/SORMAS-Project.

### Proposed Change

Adjust all (~100) references within the repository to the new URL. The PR needs to be ready to be merged once the repository was moved.

- [ ] Update URL for links to the wiki
- [ ] ~~Use relative URL where possible (e.g. links from one readme file to another within the repository).~~
- [ ] Remove or replace gitter URLs in favour of GitHub discussions

### Added Value/Benefit

* No broken links

### Acceptance Criteria

* No more references to hzi-braunschweig n GitHub

### Implementation Details

- Search for` hzi-braunschweig` within all files of the repository
- Search for `gitter `within all files of the repository

### Mockups

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #11900

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11917

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11917

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11917

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11917

**Comment by MartinWahnschaffe** [comment]
Let's disable the line length check:
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/.github/linters/.yaml-lint.yml

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11917

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11917

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=11917

**Review by StefanKock — COMMENTED** [review]
The changes look reasonable (unfortunately contains heavy code formatting on touched classes).
I don't get was up with the yml linting though.

**Review by MartinWahnschaffe — APPROVED** [review]

**Pull request merged**
