### PR TITLE
12900 - Hide jurisdiction fields in selection windows

### LINKED ISSUE #12900: Hide jurisdiction related fields in the 'Search person' and duplicate detection forms [2]
### Problem Description

When the featuretype 'HIDE_JURISDICTION_FIELDS' is set to true, we can still see the jurisdiction related fields in the forms of 'Search person' (that can be accessed from any creation form via the 'magnifying glass' icon) and in the 'Duplicate persons' and 'Duplicate detection' for cases, contacts any other entity that we have a duplicate detection for.

image
image
image

### Proposed Change

Hide jurisdiction related fields when the 'HIDE_JURISDICTION_FIELDS' is set to true in duplicate detection forms and search person form.

### Added Value/Benefit

Consistency.

### Acceptance Criteria

- [ ] if featuretype  'HIDE_JURISDICTION_FIELDS' is set to true, hide jurisdiction related fields, columns from the following forms: Search person form, duplicate detection for persons, duplicate detection for cases, contacts, any other entity for which we have duplicate detection enabled;
- [ ] use the saved default jurisdiction values configured on the respective environment instead.

### Implementation Details

_No response_

### Mockups

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MateStrysewske**
Fixes #12900

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12909

**Comment by sergiupacurariu** [comment]
On createContact - "Select source case" pop up the "Responsible district" column is visible

**Comment by sergiupacurariu** [comment]
on "Select person" pop up window - district and community columns are still visible

**Review by sergiupacurariu — CHANGES_REQUESTED** [review]
- On createContact - "Select source case" pop up the "Responsible district" column is visible
- on "Select person" pop up window - district and community columns are still visible

**Comment by MateStrysewske** [comment]
@sergiupacurariu I can't reproduce both issues. The columns are properly hidden for me. Can you please re-check and ensure that you have the HIDE_JURISDICTION_FIELDS feature turned on?

**Comment by sergiupacurariu** [comment]
Merge duplicate cases form:
	- filters still contain Jurisdiction fields
	- grid still contains Responsible district
	
Merge duplicate contacts form:
	- filters still contain Jurisdiction fields
	- grid still contains district

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12909

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12909

**Review by sergiupacurariu — APPROVED** [review]

**Pull request merged**
